# Generated by Django 6.0.4 on 2026-04-18 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Clínica Centro, Empresa XYZ, Sucursal Norte', max_length=150)),
                ('valor_hora', models.DecimalField(decimal_places=0, help_text='Valor a cobrar por hora trabajada', max_digits=10)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, help_text='Cantidad de horas. Ej: 8.5', max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_horas.establecimiento')),
            ],
        ),
    ]
