# Generated by Django 6.0.4 on 2026-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroturno',
            name='es_festivo',
            field=models.BooleanField(default=False, verbose_name='¿Es Domingo o Feriado?'),
        ),
    ]
