# Generated by Django 6.0.4 on 2026-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horas', '0002_registroturno_es_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='valor_hora_festivo',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Valor por hora domingo/feriado', max_digits=10, null=True),
        ),
    ]
