# Generated by Django 6.0.4 on 2026-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horas', '0003_establecimiento_valor_hora_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_trabajo',
            field=models.CharField(choices=[('HONORARIOS', 'Prestación de Servicios (Honorarios)'), ('EXTRAS', 'Contrato Fijo (Horas Extras)')], default='HONORARIOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(help_text='Ej: Clínica Centro, Empresa XYZ', max_length=150),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='valor_hora',
            field=models.DecimalField(decimal_places=0, help_text='Valor por hora normal o Extra al 50%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='valor_hora_festivo',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Valor por hora festivo o Extra al 100%', max_digits=10, null=True),
        ),
    ]
